version: '3.8'
services:
  kafka:
    platform: linux/amd64
    container_name: kafka-rentacar
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/opt/kafka/kafka-logs

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-t2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - .:/opt/jboss/keycloak/imports

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-rentacar
    ports: "9411"

  mongodb:
    platform: linux/amd64
    container_name: turkcell-filterdb
    image:
      mongo:4.4.6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db


volumes:
  kafka_data:
  mongodb_data: